<?php
return array(
    "admin/order/showClientTovars/([0-9]+)" => "order/showClientTovars/$1",
    "admin/order/clientShow" => "order/clientShow",
    "admin/order/recovery/([0-9]+)" => "order/recovery/$1",
    "admin/order/archive" => "order/archiveShow",
    "admin/order/delete/([0-9]+)" => "order/delete/$1",
    "admin/order/runOrder/([0-9]+)" => "order/runOrder/$1",
    "admin/order/show" => "order/show",
    "admin/registration/editProfile/([0-9]+)" => "registration/editProfile/$1",
    "admin/registration/editProfileRes" => "registration/editProfileRes",
    "admin/registration/exit" => "registration/exit",
    "admin/registration/logIn" => "registration/logIn",
    "admin/registration/addUser" => "registration/addUser",
    "admin/registration/addUserRes" => "registration/addUserRes",
    "admin/categories/del/([0-9]+)/([0-9-a-z]+)" => "categories/del/$1/$2",
    "admin/categories/delRes" => "categories/delRes",
    "admin/categories/edit/([0-9]+)" => "categories/edit/$1",
    "admin/categories/editRes" => "categories/editRes",
    "admin/tovar/del/([0-9]+)/([a-z-0-9]+)" => "tovar/del/$1/$2",
    "admin/tovar/delRes" => "tovar/delRes",
    "admin/tovar/edit/([0-9]+)" => "tovar/edit/$1",
    "admin/tovar/editRes" => "tovar/editRes",
    "admin/tovar/show/([0-9]+)" => "tovar/show/$1",
//    "admin/tovar/show" => "tovar/show",
    "admin/categories/show" => "categories/show",
    "admin/tovar/addRes" =>"tovar/addRes",
    "admin/tovar/add" => "tovar/add",
    "admin/categories/addRes" => "categories/addRes",
    "admin/categories/add" => "categories/add"
);